### ISSUE TITLE
about new idea

### ISSUE THREAD

**Issue by AstraLrus** [puppetlabs/puppet-vscode#702] opened 2020-07-23 14:40 UTC
**Summary of the new feature**

A clear and concise description of what the problem is that the new feature would solve.

For example:

---
**As a** user

**I would like to** automatically format my puppet manifests

**so that I** don't have to remember to do it myself.

**Comment by glennsarti** [comment] 2020-07-23 23:58
Duplicate of #701

**Closed by glennsarti** 2020-07-23 23:58 UTC
