### ISSUE TITLE
Extension stuck "Initializing"

### ISSUE THREAD

**Issue by chadh-mc** [puppetlabs/puppet-vscode#668] opened 2020-05-22 17:49 UTC
I noticed when I loaded vscode the the Puppet extension would print "Initializing" in the status bar and never actually load.  After talking with James in #vscode, I was able to get the extension going by explicitly setting the "install type" to "agent"

### What Versions are you running?

OS Version: MacOS Catalina 10.15.4
VSCode Version: 1.45.1
Puppet Extension Version: 0.26.1
PDK Version: 1.18.0

I also have puppet agent version 6.15 installed.

### What You Are Seeing?
"Initializing" in vscode status bar never goes away.

### What is Expected?
"initializing" goes away and extension loads up

### How Did You Get This To Happen? (Steps to Reproduce)
Here is my settings.json:

```
{
    "workbench.startupEditor": "newUntitledFile",
    "editor.fontFamily": "FiraCode-Retina",
    "editor.fontLigatures": true,
    "window.zoomLevel": 0,
    "shellcheck.customArgs": [
        "-ax -P SCRIPTDIR"
    ],
    "shellcheck.executablePath": "/Users/chadhuneycutt/.homebrew/bin/shellcheck",
    "puppet.editorService.formatOnType.enable": true,
    "puppet.installDirectory": "/opt/puppetlabs/puppet",
    "puppet.editorService.debugFilePath": "/tmp/puppet_vscode.log",
    "puppet.editorService.loglevel": "debug",
}
```

If I set "Install Type" to "auto", this happens.  If I set it to "agent", the extensions seems to load as desired.

Additional Info:
This was when vscode was launched in a control repo that has a `Gemfile.lock` created by bundler 2.1.4.  That lock file causes pdk to crash immediately.

### Output Log
```
[2020-05-22 10:43:46.014] [exthost] [error] Activating extension puppet.puppet-vscode failed due to an error:
[2020-05-22 10:43:46.014] [exthost] [error] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
	at validateString (internal/validators.js:112:11)
	at Object.join (path.js:1040:7)
	at Function.buildExecutableCommand (/Users/chadhuneycutt/.vscode/extensions/puppet.puppet-vscode-0.26.1/out/helpers/commandHelper.js:92:32)
	at Function.getLanguageServerRubyEnvFromConfiguration (/Users/chadhuneycutt/.vscode/extensions/puppet.puppet-vscode-0.26.1/out/helpers/commandHelper.js:10:27)
	at StdioConnectionHandler.createServerOptions (/Users/chadhuneycutt/.vscode/extensions/puppet.puppet-vscode-0.26.1/out/handlers/stdio.js:16:60)
	at new ConnectionHandler (/Users/chadhuneycutt/.vscode/extensions/puppet.puppet-vscode-0.26.1/out/handler.js:25:34)
	at new StdioConnectionHandler (/Users/chadhuneycutt/.vscode/extensions/puppet.puppet-vscode-0.26.1/out/handlers/stdio.js:11:9)
	at activate (/Users/chadhuneycutt/.vscode/extensions/puppet.puppet-vscode-0.26.1/out/extension.js:88:33)
	at Function._callActivateOptional (/Users/chadhuneycutt/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:824:355)
	at Function._callActivate (/Users/chadhuneycutt/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:824:6)
	at /Users/chadhuneycutt/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:822:960
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
	at async Promise.all (index 1)
```

```
DEBUG: 2020-05-22T14:43:45.991Z Installation type has changed from auto to pdk
DEBUG: 2020-05-22T14:43:45.993Z Registered extension.pdkNewModule command
DEBUG: 2020-05-22T14:43:45.993Z Registered extension.pdkNewClass command
DEBUG: 2020-05-22T14:43:45.993Z Registered extension.pdkNewTask command
DEBUG: 2020-05-22T14:43:45.993Z Registered extension.pdkValidate command
DEBUG: 2020-05-22T14:43:45.993Z Registered extension.pdkTestUnit command
DEBUG: 2020-05-22T14:43:45.993Z Found a valid Puppet installation at /opt/puppetlabs/puppet/puppet
DEBUG: 2020-05-22T14:43:45.993Z Setting status bar to Initializing
DEBUG: 2020-05-22T14:43:45.993Z Configuring language client options
DEBUG: 2020-05-22T14:43:45.993Z Creating server options
DEBUG: 2020-05-22T14:43:46.727Z pdk shell started, pid: 10068
```

**Comment by jpogran** [comment] 2020-05-22 18:15
The reason this is happening is because of `installDirectory` being set to `/opt/puppetlabs/puppet` and `installType` being left to `auto` on a system with both pdk and puppet agent. This confuses the internals which build paths to gems we need, and end up with puppet-agent paths but expecting pdk paths.

The short term workaround is to *not* set `installDirectory` if your pdk or puppet-agent is installed to the default paths, and do *not* set `installType`, or to set it to `auto`. The extension will correctly figure it the paths for pdk (even if puppet-agent is present) and work.

The longer term fix is to work on how to prevent certain settings being used with other settings, and have some validation pop up on start instead of an app crash.

PDK failing with problems with `Gemfile.lock` is a coincidence, as we are using gem libraries from inside the pdk or puppet-agent installs, not starting pdk as a process.

**Comment by chadh-mc** [comment] 2020-05-22 18:20
Yep, I can confirm that the pdk crashing is not related.   I got pdk working, but it still hangs on initializing with the path set and auto.  Either setting to "agent" or removing the install path gets it going.

**Comment by jpogran** [comment] 2020-05-26 15:53
I'm going to create a documentation issue for our docs page out of this report, with one ticket to implement more explanatory text inside the settings description and to implement some guarding to check that incompatible settings are not used together. 

The extension works when there is both pdk and agent present, and when only one is present. The problem here is that the settings for the extension are not helping the user choose successful configurations and allowing mixing of settings that then produce incorrect paths to the parts of puppet we need.

The intention for `auto` was to **not** use `installDirectory` or `installType`, so that the extension would choose whether to use `pdk` or `agent` and which paths to use itself. This was intended to make the default 'happy path' the situation where a user has `pdk` installed to the default path and not require the user to set any settings.

Items to document:

-  If you installed either `pdk` or `agent` to the default install paths, and you want the extension to figure out whether to use `pdk` or `agent`, then **do not** set any settings.
-  If you installed either pdk or agent to the default install paths, but want to choose whether to use `pdk` or `agent`, set `installType` and **omit** `installDirectory`.
-  If you installed either pdk or agent to custom install paths, you **must specify** `installType` as either `agent` or `pdk`, **and set** `installDirectory` to the correct path.

**Comment by rgevaert** [comment] 2020-07-15 15:35
Hi, I have a similar issue. I had to install pdk through ruby gem command. It installed pdk in /usr/local/bin/pdk. And thus I configured the plugin to load it from that path:

```
    "puppet.installType": "pdk",
    "puppet.installDirectory": "/usr/local/bin/pdk",
    "puppet.editorService.formatOnType.enable": true,
    "puppet.editorService.debugFilePath": "/tmp/puppet.log",
    "puppet.editorService.loglevel": "debug",
    "puppet.editorService.featureFlags": [
```

However it is still stuck:
![image](https://user-images.githubusercontent.com/66934/87565165-95a7a080-c6c1-11ea-8d27-16b4c2208dfe.png)

**Comment by rgevaert** [comment] 2020-07-16 07:12
Thanks James. After a 1.5y "sabatical" from using Puppet I've been out of touch with all developments. Combine that with switching to vscode (from vim) this are all new things! I'll just stick with the puppet agent for now. But if I need to I'll look at the remote container extension!

**Comment by jpogran** [comment] 2021-01-30 15:54
All, apologies for the elapsed time but I am back to working on the extension full time.

This issue has several different threads in it at one time so it is hard to determine if they have been resolved. I'm closing this issue out but if you are tagged in this thread, please open a new issue referring to this one and I'll get it on the board to be investigated for the 1.2.0 release.

**Closed by jpogran** 2021-01-30 15:54 UTC
Labels: awaiting-approval, documentation
