### ISSUE TITLE
Error starting extension with PDK 2.0

### ISSUE THREAD

**Issue by ShukiBT** [puppetlabs/puppet-vscode#730] opened 2021-03-04 09:37 UTC
[puppet_server.log](https://github.com/puppetlabs/puppet-vscode/files/6082287/puppet_server.log)

### What Versions are you running?

OS Version: Win
VSCode Version : 1.53.2
Puppet Extension Version: 1.1.0
PDK Version: 2.7.2 (gem 2.7.0) 

### What You Are Seeing?
Error in VSCode when the language server for puppet starting up

### Output Log
[puppet_server.log](https://github.com/puppetlabs/puppet-vscode/files/6082384/puppet_server.log)
[puppet_server.txt](https://github.com/puppetlabs/puppet-vscode/files/6082389/puppet_server.txt)

**Comment by jpogran** [comment] 2021-03-04 14:22
I'll review the logs. In the mean time @ShukiBT, can you reply with the actual versions instead of 'latest'? It's not helpful in trying to setup a repro environment when latest can mean different things depending on when the ticket was looked at.

Also, do you mean PDK 2.0? There isn't a 2.7 out

**Comment by ShukiBT** [comment] 2021-03-04 14:26
VSCode Version : 1.53.2
Puppet Extension Version: 1.1.0
PDK Version: 2.7.2 (gem 2.7.0)

**Comment by glennsarti** [comment] 2021-03-06 10:25
Confirmed.  Using PDK 2.0.0.  Setting the appropriate ENV Vars

``` text
@ECHO OFF

SET PUPPET_BASEDIR=C:\Progra~1\Puppet~1\DevelopmentKit
SET PUPPET_NIXBASEDIR=C:/Progra~1/Puppet~1/DevelopmentKit

SET DEVKIT_BASEDIR=%PUPPET_BASEDIR%
SET RUBY_DIR=%DEVKIT_BASEDIR%\private\ruby\2.7.2
SET RUBYLIB=%PUPPET_NIXBASEDIR%/lib

SET PATH=%DEVKIT_BASEDIR%\bin;%RUBY_DIR%\bin;%PATH%
SET RUBYOPT=rubygems

SET GEM_HOME=%PUPPET_NIXBASEDIR%/share/cache/ruby/2.7.0
SET GEM_PATH=%DEVKIT_BASEDIR%\private\ruby\2.7.2\lib\ruby\gems\2.7.0;%PUPPET_NIXBASEDIR%/share/cache/ruby/2.7.0;%PUPPET_BASEDIR%\private\puppet\ruby\2.7.0
```

Running editor services from source:

``` text
:\Source\puppet-editor-services>ruby puppet-languageserver --port=9000 --ip=0.0.0.0 --debug=STDOUT --timeout=0
I, [2021-03-06T18:23:15.914847 #3436]  INFO -- : Language Server is v1.0.1
D, [2021-03-06T18:23:15.915123 #3436] DEBUG -- : Loading gems...
E, [2021-03-06T18:23:24.499971 #3436] ERROR -- : Error while loading a critical gem: cannot load such file -- ffi_c ["C:/Progra~1/Puppet~1/DevelopmentKit/private/ruby/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:155:in `require'", "C:/Progra~1/Puppet~1/DevelopmentKit/private/ruby/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:155:in `require'", "C:/Progra~1/Puppet~1/DevelopmentKit/private/puppet/ruby/2.7.0/gems/ffi-1.14.2-x64-mingw32/lib/ffi.rb:6:in `rescue in <top (required)>'", "C:/Progra~1/Puppet~1/DevelopmentKit/private/puppet/ruby/2.7.0/gems/ffi-1.14.2-x64-mingw32/lib/ffi.rb:3:in `<top (required)>'", "C:/Progra~1/Puppet~1/DevelopmentKit/private/ruby/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:103:in `require'", "C:/Progra~1/Puppet~1/DevelopmentKit/private/ruby/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:103:in `require'", "C:/Progra~1/Puppet~1/DevelopmentKit/private/puppet/ruby/2.7.0/gems/puppet-7.4.1-x64-mingw32/lib/puppet/ffi/windows.rb:1:in `<top (required)>'", "C:/Progra~1/Puppet~1/DevelopmentKit/private/ruby/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:103:in `require'", "C:/Progra~1/Puppet~1/DevelopmentKit/private/ruby/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:103:in `require'", "C:/Progra~1/Puppet~1/DevelopmentKit/pr
...
```

**Comment by glennsarti** [comment] 2021-03-06 10:25
Probably means we're missing a GEM_PATH ... OR PDK 2.0.0 is packaged wrong

**Comment by glennsarti** [comment] 2021-03-06 10:35
Using the PDK bundled environment it works

```
C:\Source\fakemod\tmp> pdk bundle exec cmd
pdk (INFO): Using Ruby 2.7.2
pdk (INFO): Using Puppet 7.4.1
Microsoft Windows [Version 10.0.19041.804]
(c) 2020 Microsoft Corporation. All rights reserved.



C:\Source\puppet-editor-services>ruby puppet-languageserver --port=9000 --ip=0.0.0.0 --debug=STDOUT --timeout=0
I, [2021-03-06T18:34:06.709446 #21948]  INFO -- : Language Server is v1.0.1
D, [2021-03-06T18:34:06.709722 #21948] DEBUG -- : Loading gems...
I, [2021-03-06T18:34:14.387800 #21948]  INFO -- : Using Puppet v7.4.1
I, [2021-03-06T18:34:14.388070 #21948]  INFO -- : Using Facter v4.0.51
D, [2021-03-06T18:34:14.388318 #21948] DEBUG -- : Detected additional puppet settings []
I, [2021-03-06T18:34:14.486737 #21948]  INFO -- : Initializing settings...
I, [2021-03-06T18:34:14.487754 #21948]  INFO -- : Starting RPC Server...
D, [2021-03-06T18:34:14.561102 #21948] DEBUG -- : Using TCP Server
D, [2021-03-06T18:34:14.570154 #21948] DEBUG -- : TCPSRV: Services running. Press ^C to stop
D, [2021-03-06T18:34:14.570374 #21948] DEBUG -- : TCPSRV: Will stop the server when client disconnects
LANGUAGE SERVER RUNNING 0.0.0.0:9000
D, [2021-03-06T18:34:14.571464 #21948] DEBUG -- : TCPSRV: Started listening on 0.0.0.0:9000.
```

**Comment by glennsarti** [comment] 2021-03-06 10:36
Looks like Pup7 or Ruby7 need something different in the ENV Vars 😢

**Comment by glennsarti** [comment] 2021-03-06 11:57
After a lot of combination changes for env vars, I think I've hit on the correct one.  Need to add this to the path (obviously relative to PDK install but ...)

`C:/Program Files/Puppet Labs/DevelopmentKit/private/git/mingw64/bin`

Specifically it's loading `libssp-0.dll`

Why on earth Puppet requires a DLL in the Mingw64 port of git I have NO IDEA 🤷‍♂️🤷‍♂️

**Comment by glennsarti** [comment] 2021-03-06 11:59
Those path changes have been in PDK since 1.2.0 (https://github.com/puppetlabs/pdk/commit/2514f8bbecffd162095ccb74d055913b7e013cb7) so I suspect the packaging for PDK 2.0.0 is broken for some DLLs 😭

**Comment by ShukiBT** [comment] 2021-03-07 07:05
So, what is the solution? workaround?

**Comment by jpogran** [comment] 2021-03-07 21:32
@ShukiBT Right now we don't have anything for you. Glenn and I are still investigating the issue

**Comment by jpogran** [comment] 2021-03-08 20:16
Well that was fun spelunking into puppet and ruby internals! Thanks for the pointer @glennsarti, I don't think I would have found this without it.

I started by opening a Puppet module using VS Code and had procmon running. Then, using Glenn's pointer, I looked for where `libssp-0.dll` was referenced and found:

![image](https://user-images.githubusercontent.com/272569/110366734-ab812180-8014-11eb-8977-5f6f9d028088.png)

Seemed like it was attempted during the `ffi` require. I went looking at the ffi repo and found https://github.com/ffi/ffi/issues/868. The TLDR of that is that `ffi` v1.14.2 was built with a newer gcc version which requires `libssp-0.dll`, but that dll is not present in the standard ruby distribution. Since we bundle git binaries in PDK and adds those binaries to the PATH it never hit this issue, but anything else that didn't would hit it.

In the long term this will be fixed when Puppet moves to the latest version of the `ffi` gem. In the short term I will have to add the path to our execution code to workaround this.

@ShukiBT As a temporary workaround until I get a release out, you can add `C:/Program Files/Puppet Labs/DevelopmentKit/private/git/mingw64/bin` to your PATH before opening VS Code and things should work. I'll update this ticket when I have a PR ready

**Comment by ShukiBT** [comment] 2021-03-09 07:44
Big Thanks @jpogran  and @glennsarti !
The workaround works perfectly.
waiting for the release..

**Comment by ShukiBT** [comment] 2021-03-13 15:58
@jpogran / @glennsarti  
New error after VS Code update:
**DEBUG: 2021-03-13T15:56:41.691Z pdk shell started, pid: 6676**
C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.7.2/lib/ruby/2.7.0/fileutils.rb:250:in `mkdir': No such file or directory @ dir_s_mkdir - H:/.puppetlabs (Errno::ENOENT)
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.7.2/lib/ruby/2.7.0/fileutils.rb:250:in `fu_mkdir'

**Comment by ShukiBT** [comment] 2021-03-13 15:58
EBUG: 2021-03-13T15:56:41.691Z pdk shell started, pid: 6676
C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.7.2/lib/ruby/2.7.0/fileutils.rb:250:in `mkdir': No such file or directory @ dir_s_mkdir - H:/.puppetlabs (Errno::ENOENT)
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.7.2/lib/ruby/2.7.0/fileutils.rb:250:in `fu_mkdir'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.7.2/lib/ruby/2.7.0/fileutils.rb:228:in `block (2 levels) in mkdir_p'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.7.2/lib/ruby/2.7.0/fileutils.rb:226:in `reverse_each'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.7.2/lib/ruby/2.7.0/fileutils.rb:226:in `block in mkdir_p'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.7.2/lib/ruby/2.7.0/fileutils.rb:211:in `each'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.7.2/lib/ruby/2.7.0/fileutils.rb:211:in `mkdir_p'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/puppet/ruby/2.7.0/gems/puppet-7.4.1-x64-mingw32/lib/puppet/settings.rb:408:in `create_ancestors'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/puppet/ruby/2.7.0/gems/puppet-7.4.1-x64-mingw32/lib/puppet/settings.rb:393:in `block in initialize_app_defaults'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/puppet/ruby/2.7.0/gems/puppet-7.4.1-x64-mingw32/lib/puppet/settings.rb:392:in `each'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/puppet/ruby/2.7.0/gems/puppet-7.4.1-x64-mingw32/lib/puppet/settings.rb:392:in `initialize_app_defaults'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/puppet/ruby/2.7.0/gems/puppet-7.4.1-x64-mingw32/lib/puppet.rb:180:in `do_initialize_settings_for_run_mode'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/puppet/ruby/2.7.0/gems/puppet-7.4.1-x64-mingw32/lib/puppet.rb:153:in `initialize_settings'
	from c:/Users/Shuki.Yulzari/.vscode/extensions/puppet.puppet-vscode-1.1.0/vendor/languageserver/lib/puppet_languageserver.rb:222:in `init_puppet'
	from c:/Users/Shuki.Yulzari/.vscode/extensions/puppet.puppet-vscode-1.1.0/vendor/languageserver/puppet-languageserver:13:in `<main>'
[Info  - 5:56:51 PM] Connection to server got closed. Server will restart.
C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.7.2/lib/ruby/2.7.0/fileutils.rb:250:in `mkdir': No such file or directory @ dir_s_mkdir - H:/.puppetlabs (Errno::ENOENT)
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.7.2/lib/ruby/2.7.0/fileutils.rb:250:in `fu_mkdir'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.7.2/lib/ruby/2.7.0/fileutils.rb:228:in `block (2 levels) in mkdir_p'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.7.2/lib/ruby/2.7.0/fileutils.rb:226:in `reverse_each'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.7.2/lib/ruby/2.7.0/fileutils.rb:226:in `block in mkdir_p'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.7.2/lib/ruby/2.7.0/fileutils.rb:211:in `each'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.7.2/lib/ruby/2.7.0/fileutils.rb:211:in `mkdir_p'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/puppet/ruby/2.7.0/gems/puppet-7.4.1-x64-mingw32/lib/puppet/settings.rb:408:in `create_ancestors'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/puppet/ruby/2.7.0/gems/puppet-7.4.1-x64-mingw32/lib/puppet/settings.rb:393:in `block in initialize_app_defaults'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/puppet/ruby/2.7.0/gems/puppet-7.4.1-x64-mingw32/lib/puppet/settings.rb:392:in `each'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/puppet/ruby/2.7.0/gems/puppet-7.4.1-x64-mingw32/lib/puppet/settings.rb:392:in `initialize_app_defaults'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/puppet/ruby/2.7.0/gems/puppet-7.4.1-x64-mingw32/lib/puppet.rb:180:in `do_initialize_settings_for_run_mode'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/puppet/ruby/2.7.0/gems/puppet-7.4.1-x64-mingw32/lib/puppet.rb:153:in `initialize_settings'
	from c:/Users/Shuki.Yulzari/.vscode/extensions/puppet.puppet-vscode-1.1.0/vendor/languageserver/lib/puppet_languageserver.rb:222:in `init_puppet'
	from c:/Users/Shuki.Yulzari/.vscode/extensions/puppet.puppet-vscode-1.1.0/vendor/languageserver/puppet-languageserver:13:in `<main>'
[Info  - 5:57:00 PM] Connection to server got closed. Server will restart.
C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.7.2/lib/ruby/2.7.0/fileutils.rb:250:in `mkdir': No such file or directory @ dir_s_mkdir - H:/.puppetlabs (Errno::ENOENT)
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.7.2/lib/ruby/2.7.0/fileutils.rb:250:in `fu_mkdir'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.7.2/lib/ruby/2.7.0/fileutils.rb:228:in `block (2 levels) in mkdir_p'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.7.2/lib/ruby/2.7.0/fileutils.rb:226:in `reverse_each'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.7.2/lib/ruby/2.7.0/fileutils.rb:226:in `block in mkdir_p'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.7.2/lib/ruby/2.7.0/fileutils.rb:211:in `each'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.7.2/lib/ruby/2.7.0/fileutils.rb:211:in `mkdir_p'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/puppet/ruby/2.7.0/gems/puppet-7.4.1-x64-mingw32/lib/puppet/settings.rb:408:in `create_ancestors'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/puppet/ruby/2.7.0/gems/puppet-7.4.1-x64-mingw32/lib/puppet/settings.rb:393:in `block in initialize_app_defaults'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/puppet/ruby/2.7.0/gems/puppet-7.4.1-x64-mingw32/lib/puppet/settings.rb:392:in `each'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/puppet/ruby/2.7.0/gems/puppet-7.4.1-x64-mingw32/lib/puppet/settings.rb:392:in `initialize_app_defaults'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/puppet/ruby/2.7.0/gems/puppet-7.4.1-x64-mingw32/lib/puppet.rb:180:in `do_initialize_settings_for_run_mode'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/puppet/ruby/2.7.0/gems/puppet-7.4.1-x64-mingw32/lib/puppet.rb:153:in `initialize_settings'
	from c:/Users/Shuki.Yulzari/.vscode/extensions/puppet.puppet-vscode-1.1.0/vendor/languageserver/lib/puppet_languageserver.rb:222:in `init_puppet'
	from c:/Users/Shuki.Yulzari/.vscode/extensions/puppet.puppet-vscode-1.1.0/vendor/languageserver/puppet-languageserver:13:in `<main>'
[Info  - 5:57:09 PM] Connection to server got closed. Server will restart.
C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.7.2/lib/ruby/2.7.0/fileutils.rb:250:in `mkdir': No such file or directory @ dir_s_mkdir - H:/.puppetlabs (Errno::ENOENT)
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.7.2/lib/ruby/2.7.0/fileutils.rb:250:in `fu_mkdir'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.7.2/lib/ruby/2.7.0/fileutils.rb:228:in `block (2 levels) in mkdir_p'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.7.2/lib/ruby/2.7.0/fileutils.rb:226:in `reverse_each'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.7.2/lib/ruby/2.7.0/fileutils.rb:226:in `block in mkdir_p'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.7.2/lib/ruby/2.7.0/fileutils.rb:211:in `each'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.7.2/lib/ruby/2.7.0/fileutils.rb:211:in `mkdir_p'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/puppet/ruby/2.7.0/gems/puppet-7.4.1-x64-mingw32/lib/puppet/settings.rb:408:in `create_ancestors'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/puppet/ruby/2.7.0/gems/puppet-7.4.1-x64-mingw32/lib/puppet/settings.rb:393:in `block in initialize_app_defaults'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/puppet/ruby/2.7.0/gems/puppet-7.4.1-x64-mingw32/lib/puppet/settings.rb:392:in `each'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/puppet/ruby/2.7.0/gems/puppet-7.4.1-x64-mingw32/lib/puppet/settings.rb:392:in `initialize_app_defaults'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/puppet/ruby/2.7.0/gems/puppet-7.4.1-x64-mingw32/lib/puppet.rb:180:in `do_initialize_settings_for_run_mode'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/puppet/ruby/2.7.0/gems/puppet-7.4.1-x64-mingw32/lib/puppet.rb:153:in `initialize_settings'
	from c:/Users/Shuki.Yulzari/.vscode/extensions/puppet.puppet-vscode-1.1.0/vendor/languageserver/lib/puppet_languageserver.rb:222:in `init_puppet'
	from c:/Users/Shuki.Yulzari/.vscode/extensions/puppet.puppet-vscode-1.1.0/vendor/languageserver/puppet-languageserver:13:in `<main>'
[Info  - 5:57:19 PM] Connection to server got closed. Server will restart.
C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.7.2/lib/ruby/2.7.0/fileutils.rb:250:in `mkdir': No such file or directory @ dir_s_mkdir - H:/.puppetlabs (Errno::ENOENT)
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.7.2/lib/ruby/2.7.0/fileutils.rb:250:in `fu_mkdir'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.7.2/lib/ruby/2.7.0/fileutils.rb:228:in `block (2 levels) in mkdir_p'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.7.2/lib/ruby/2.7.0/fileutils.rb:226:in `reverse_each'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.7.2/lib/ruby/2.7.0/fileutils.rb:226:in `block in mkdir_p'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.7.2/lib/ruby/2.7.0/fileutils.rb:211:in `each'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.7.2/lib/ruby/2.7.0/fileutils.rb:211:in `mkdir_p'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/puppet/ruby/2.7.0/gems/puppet-7.4.1-x64-mingw32/lib/puppet/settings.rb:408:in `create_ancestors'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/puppet/ruby/2.7.0/gems/puppet-7.4.1-x64-mingw32/lib/puppet/settings.rb:393:in `block in initialize_app_defaults'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/puppet/ruby/2.7.0/gems/puppet-7.4.1-x64-mingw32/lib/puppet/settings.rb:392:in `each'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/puppet/ruby/2.7.0/gems/puppet-7.4.1-x64-mingw32/lib/puppet/settings.rb:392:in `initialize_app_defaults'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/puppet/ruby/2.7.0/gems/puppet-7.4.1-x64-mingw32/lib/puppet.rb:180:in `do_initialize_settings_for_run_mode'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/puppet/ruby/2.7.0/gems/puppet-7.4.1-x64-mingw32/lib/puppet.rb:153:in `initialize_settings'
	from c:/Users/Shuki.Yulzari/.vscode/extensions/puppet.puppet-vscode-1.1.0/vendor/languageserver/lib/puppet_languageserver.rb:222:in `init_puppet'
	from c:/Users/Shuki.Yulzari/.vscode/extensions/puppet.puppet-vscode-1.1.0/vendor/languageserver/puppet-languageserver:13:in `<main>'
[Error - 5:57:27 PM] Connection to server got closed. Server will not be restarted.

**Comment by jpogran** [comment] 2021-03-15 14:18
@ShukiBT I combined and reformatted your error message for better readability. I am pretty sure this is a different issue related to attempting to use puppet with a redirected home directory (`H:/.puppetlabs`) but I can't remember the fix. I think @glennsarti was the one that investigated that.

**Closed** 2021-03-31 17:23 UTC
